name:                resource-id
version:             0.1.0.0
github:              "yuanwang-wf/resource-id"
license:             BSD3
author:              "Yuan Wang"
maintainer:          "yuan.wang@workiva.com"
copyright:           "2019 Yuan Wang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yuanwang-wf/resource-id#readme>

dependencies:
- base >= 4.7 && < 5
- base64-bytestring
- bytestring
- pretty-terminal
- text

library:
  source-dirs: src

executables:
  rid:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - resource-id

tests:
  resource-id-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - resource-id
